# Site settings
title: Westbury's Weblog.
tagline:
email: tomwestbury1@gmail.com
description:
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.cathxrsis.co.uk" # the base hostname & protocol for your site
twitter_username: cathxrsis
github_username:  cathxrsis

# Build settings
markdown: kramdown

diqus: tomwestbury

gems:
 - jekyll-sitemap
